name: DamageIndicator
version: 2.1.0
main: io.github.stealingdapenta.damageindicator.DamageIndicator
author: StealingDaPenta
api-version: 1.21

description: >
  The best Damage Indicator in the game! 
  Features floating damage numbers, health bars, holograms, and full customization.

# === Commands ===
commands:
  reload:
    description: Reload the configuration without restarting the server.
    usage: /<command>
    aliases: [ config, load, restart ]

  arearemove:
    description: Remove nearby stuck damage indicator holograms (from this plugin only).
    usage: /<command>

  arearename:
    description: Rename nearby stuck health bars. Warning! This will remove ALL custom names in the area!
    usage: /<command>

# === Permissions ===
permissions:
  damageindicator.reload:
    description: Allows the user to reload the plugin config using /reload or its aliases.
    default: op

  damageindicator.arearemove:
    description: Allows the user to execute /arearemove to clean up local indicators.
    default: op

  damageindicator.arearename:
    description: Allows the user to execute /arearename to rename local indicators. Warning! This will remove ALL custom names in the area!
    default: op
