name: damageindicator
version: 1.3.3
main: io.github.stealingdapenta.damageindicator.DamageIndicator
author: StealingDaPenta
description: The best Damage Indicator in the game!
api-version: 1.20.6

commands:
  reload:
    description: Reload the configuration file without having to reboot the server.
    usage: /<command>
    aliases: [ config, load, restart ]

  arearemove:
    description: Remove stuck damage indicator related entities around you. This will kill all nearby holographs, but from this plugin only.
    usage: /<command>


permissions:
  damageindicator.reload:
    description: Allow usage of /config
    default: op
  damageindicator.arearemove:
    description: Allow usage of /arearemove
    default: op
